### ISSUE TITLE
Error Overwritting 

### ISSUE THREAD

**Issue by amoprocedures** [ashinzekene/rave-simple#7]
how can i over-write the error incase the response from the flutter occurs
Eg. user has insufficient funds on his account.
![Opera Snapshot_2020-05-01_203546_localhost](https://user-images.githubusercontent.com/39941582/80826633-3d492280-8beb-11ea-94ab-503b51dbb95b.png)

**Comment by ashinzekene** [comment]
As far as I know you can't do that with [rave-inline](https://developer.flutterwave.com/docs/rave-inline-1)

**Comment by amoprocedures** [comment]
ok @ashinzekene
